-- Immobiliare.ai Database Schema
-- Phase 2: Production Migration

-- 1. PROPERTIES: The Core Table with Hybrid SQL + JSONB
CREATE TABLE IF NOT EXISTS properties (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Standard Search Fields (Indexed)
    title TEXT NOT NULL,
    price INTEGER,
    sqm INTEGER,
    rooms INTEGER,      -- "Locali"
    bathrooms INTEGER,  -- "Bagni"
    floor INTEGER,      -- "Piano"
    total_floors INTEGER, -- "Piani edificio"
    elevator BOOLEAN,   -- "Ascensore"
    zone TEXT,          -- "Città Studi", "Brera", "Portello"
    city TEXT,          -- "Milano", "Roma", "Torino"
    address TEXT,
    
    -- FLEXIBLE SPECS (The "Real Deal" Data)
    -- Stores the "Caratteristiche" block (Heating, AC, Contract, Furnished status)
    -- Example: {"heating": "Centralizzato", "ac": "Autonomo", "contract": "Vendita", "type": "Appartamento"}
    specs JSONB DEFAULT '{}'::jsonb,
    
    -- AI Content
    description_original TEXT, -- Original agent/owner description
    description_ai TEXT,       -- Generated by Gemini Flash
    ai_vibe_tags TEXT[]        -- ["bright", "student-friendly", "luxury"]
);

-- 2. PROPERTY_IMAGES: 1-to-Many Relationship
CREATE TABLE IF NOT EXISTS property_images (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    property_id UUID REFERENCES properties(id) ON DELETE CASCADE,
    
    storage_url TEXT NOT NULL, -- Public Supabase URL or external URL
    
    -- AI Vision Metadata
    room_type TEXT,       -- "Kitchen", "Bedroom", "Living Room"
    renovation_potential TEXT, -- "High", "Medium", "Low"
    
    is_main BOOLEAN DEFAULT FALSE
);

-- 3. CREATE INDEXES for Performance
CREATE INDEX IF NOT EXISTS idx_properties_zone ON properties(zone);
CREATE INDEX IF NOT EXISTS idx_properties_price ON properties(price);
CREATE INDEX IF NOT EXISTS idx_properties_rooms ON properties(rooms);
CREATE INDEX IF NOT EXISTS idx_properties_specs ON properties USING GIN (specs);
CREATE INDEX IF NOT EXISTS idx_property_images_property_id ON property_images(property_id);

-- 4. ENABLE ROW LEVEL SECURITY (Optional for MVP, recommended for production)
-- ALTER TABLE properties ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE property_images ENABLE ROW LEVEL SECURITY;

-- 5. CREATE POLICY for public read access (uncomment if using RLS)
-- CREATE POLICY "Allow public read access" ON properties FOR SELECT USING (true);
-- CREATE POLICY "Allow public read access" ON property_images FOR SELECT USING (true);
